[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**"]

[[redirects]]
  # Redirecci칩n para funciones de Netlify
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Redirecci칩n para todas las dem치s rutas (Single Page Application)
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Configuraci칩n de encabezados CORS para las funciones
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "no-cache"